export const UPDATE_GNOMES_DATA = "UPDATE_GNOMES_DATA";
export const UPDATE_GNOME_ID = "UPDATE_GNOME_ID";
export const UPDATE_GNOME_NAME = "UPDATE_GNOME_NAME";
export const CLEAN_SEARCH = "CLEAN_SEARCH";
export const FETCH_GNOMES_FAILED = "FETCH_GNOMES_FAILED";